# ---------------------
# GLOBAL SITE SETTINGS
# ---------------------

cname: clubssa.yourwebvisual.com

# META
title: "Clubs SA"
seo_title: ""
company: "Clubs SA"
description: ""

# CONTACT
email: admin@clubssa.com.au
phone: (08) 8290 2200
fax: (08) 8290 2222

# OFFICES
offices:
  - title: South Australia
    address: "222a Henley Beach Rd<br> Torrensville, SA 5031"
    phone: (08) 8290 2200
    fax: (08) 8290 2222

# SOCIAL MEDIA
facebook: "https://www.facebook.com/CLUBSSA"
linked_in: ""
google_plus: ""

# GOOGLE
google_map: ""
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://www.muchmedia.com.au
  logo: /img/template/much-media-logo.svg
  description: Website by Much Media

# BREAKPOINTS
breakpoints:
  xs : 0
  sm : 544
  md : 768
  lg : 992
  xl : 1350